language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install
  email@garoevans.pagerduty.com

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    recipients:
      - email@garoevans.pagerduty.com
